### ISSUE TITLE
Use with node.js

### ISSUE THREAD

**Issue by drmrbrewer** [JackBister/async-lz-string#9]
Looks like a useful library... is it useable as a module for node.js?

Thanks.

**Comment by JackBister** [comment]
Hello! It should work in node.js as well. The only API it uses that isn't just standard JavaScript is setTimeout, which is available in node too. Let me know if you try it and there's any problems!

**Comment by drmrbrewer** [comment]
Thanks for the reply.  When I tried to `require` the module in node.js, in the same way as for other modules, calling an async-lz-string function resulted in an error along the lines of `window` is not defined.  Probably the module importing bit just needs a tweak to work out of the box in node?  Anyway, instead I grabbed the original lz-string code and just added in the `Promise` and `setTimeout` bits into that myself to achieve the same result, and I can just require that modified code into my node code and it works just fine.  Thanks.

**Comment by JackBister** [comment]
I see the problem, when I have been running it in Node I have been recompiling the library from typescript which made it work, but when downloading the version that is on npm the compiled .js file uses window. I am working on fixing this.

**Comment by JackBister** [comment]
@drmrbrewer I just published a new version to npm (1.0.3) which should fix this, it would be great if you can test that version and see if it works for you.

I added [this](https://github.com/JackBister/async-lz-string/blob/master/test/node-test.js) test which runs against the compiled output and didn't work before but now works.

**Comment by drmrbrewer** [comment]
Yep, works fine in node.js with:

    const { compressToUTF16, decompressFromUTF16 } = require('async-lz-string');

I have since realised that this library doesn't currently support the `EncodedURIComponent` variants of compress/decompress, which I need, so I'll continue with my own hacked version of the original for now, but thanks for making this node-ready!  

I also find it useful (in my own hacked version) to be able to tailor the count interval between the `setTimeout` "break points"... I am not really sure what would be considered "optimal" but I like to be able to tweak that parameter anyway.  Yours are hard-coded at `10000` and `20000`.
